name: blip2multiview
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=py310h06a4308_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - comm=0.2.1=py310h06a4308_0
  - debugpy=1.8.16=py310hbdd6827_0
  - decorator=5.2.1=py310h06a4308_0
  - exceptiongroup=1.2.0=py310h06a4308_0
  - executing=2.2.1=py310h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ipykernel=6.30.1=py310h06a4308_0
  - ipython=8.30.0=py310h06a4308_0
  - jedi=0.19.2=py310h06a4308_0
  - jupyter_client=8.6.3=py310h06a4308_0
  - jupyter_core=5.8.1=py310h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.20=heac8642_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - matplotlib-inline=0.1.7=py310h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py310h06a4308_0
  - parso=0.8.4=py310h06a4308_0
  - pexpect=4.9.0=py310h06a4308_0
  - pip=25.2=pyhc872135_0
  - platformdirs=4.3.7=py310h06a4308_0
  - prompt-toolkit=3.0.43=py310h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=7.0.0=py310hee96239_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.3=py310h06a4308_0
  - pygments=2.19.1=py310h06a4308_0
  - python=3.10.18=h1a3bd86_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - pyzmq=27.1.0=py310hcf8288c_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py310h06a4308_0
  - six=1.17.0=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=py310h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py310h5eee18b_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - wcwidth=0.2.13=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - beautifulsoup4==4.14.2
      - bert-score==0.3.13
      - bitsandbytes==0.48.1
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.3.0
      - datasets==4.1.1
      - dotmap==1.3.30
      - gdown==5.2.0
      - h5py==3.15.1
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - idna==3.4
      - imageio==2.37.0
      - iniconfig==2.3.0
      - joblib==1.5.2
      - jsonpickle==4.1.1
      - markupsafe==2.1.5
      - nltk==3.9.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - peft==0.17.1
      - pillow==11.0.0
      - pluggy==1.6.0
      - pyarrow==21.0.0
      - pyparsing==3.2.5
      - pysocks==1.7.1
      - pytest==8.4.2
      - pytz==2025.2
      - pyyaml==6.0.3
      - radgraph==0.1.18
      - requests==2.32.5
      - rouge-score==0.1.2
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - soupsieve==2.8
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - transformers==4.57.0
      - triton==3.4.0
      - urllib3==1.26.13
